/**
 * generated by Xtext 2.12.0
 */
package org.xtext.ifcbrickconvert.ifcBrick;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>CSV</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.ifcbrickconvert.ifcBrick.CSV#getA <em>A</em>}</li>
 *   <li>{@link org.xtext.ifcbrickconvert.ifcBrick.CSV#getB <em>B</em>}</li>
 * </ul>
 *
 * @see org.xtext.ifcbrickconvert.ifcBrick.IfcBrickPackage#getCSV()
 * @model
 * @generated
 */
public interface CSV extends EObject
{
  /**
   * Returns the value of the '<em><b>A</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>A</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>A</em>' attribute.
   * @see #setA(int)
   * @see org.xtext.ifcbrickconvert.ifcBrick.IfcBrickPackage#getCSV_A()
   * @model
   * @generated
   */
  int getA();

  /**
   * Sets the value of the '{@link org.xtext.ifcbrickconvert.ifcBrick.CSV#getA <em>A</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>A</em>' attribute.
   * @see #getA()
   * @generated
   */
  void setA(int value);

  /**
   * Returns the value of the '<em><b>B</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>B</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>B</em>' attribute.
   * @see #setB(int)
   * @see org.xtext.ifcbrickconvert.ifcBrick.IfcBrickPackage#getCSV_B()
   * @model
   * @generated
   */
  int getB();

  /**
   * Sets the value of the '{@link org.xtext.ifcbrickconvert.ifcBrick.CSV#getB <em>B</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>B</em>' attribute.
   * @see #getB()
   * @generated
   */
  void setB(int value);

} // CSV
