/**
 * generated by Xtext 2.12.0
 */
package org.xtext.ifcbrickconvert.ifcBrick;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Entity</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.ifcbrickconvert.ifcBrick.Entity#getDefinition <em>Definition</em>}</li>
 *   <li>{@link org.xtext.ifcbrickconvert.ifcBrick.Entity#getAttributeCollection <em>Attribute Collection</em>}</li>
 * </ul>
 *
 * @see org.xtext.ifcbrickconvert.ifcBrick.IfcBrickPackage#getEntity()
 * @model
 * @generated
 */
public interface Entity extends EObject
{
  /**
   * Returns the value of the '<em><b>Definition</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Definition</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Definition</em>' attribute.
   * @see #setDefinition(String)
   * @see org.xtext.ifcbrickconvert.ifcBrick.IfcBrickPackage#getEntity_Definition()
   * @model
   * @generated
   */
  String getDefinition();

  /**
   * Sets the value of the '{@link org.xtext.ifcbrickconvert.ifcBrick.Entity#getDefinition <em>Definition</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Definition</em>' attribute.
   * @see #getDefinition()
   * @generated
   */
  void setDefinition(String value);

  /**
   * Returns the value of the '<em><b>Attribute Collection</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Attribute Collection</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attribute Collection</em>' containment reference.
   * @see #setAttributeCollection(AttributeCollection)
   * @see org.xtext.ifcbrickconvert.ifcBrick.IfcBrickPackage#getEntity_AttributeCollection()
   * @model containment="true"
   * @generated
   */
  AttributeCollection getAttributeCollection();

  /**
   * Sets the value of the '{@link org.xtext.ifcbrickconvert.ifcBrick.Entity#getAttributeCollection <em>Attribute Collection</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Attribute Collection</em>' containment reference.
   * @see #getAttributeCollection()
   * @generated
   */
  void setAttributeCollection(AttributeCollection value);

} // Entity
