/**
 * generated by Xtext 2.12.0
 */
package org.xtext.ifcbrickconvert.ifcBrick;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Header</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.ifcbrickconvert.ifcBrick.Header#getHeaderEntities <em>Header Entities</em>}</li>
 * </ul>
 *
 * @see org.xtext.ifcbrickconvert.ifcBrick.IfcBrickPackage#getHeader()
 * @model
 * @generated
 */
public interface Header extends EObject
{
  /**
   * Returns the value of the '<em><b>Header Entities</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.ifcbrickconvert.ifcBrick.EntityTerminated}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Header Entities</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Header Entities</em>' containment reference list.
   * @see org.xtext.ifcbrickconvert.ifcBrick.IfcBrickPackage#getHeader_HeaderEntities()
   * @model containment="true"
   * @generated
   */
  EList<EntityTerminated> getHeaderEntities();

} // Header
