/**
 * generated by Xtext 2.12.0
 */
package org.xtext.ifcbrickconvert.ifcBrick;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.ifcbrickconvert.ifcBrick.IfcBrickFactory
 * @model kind="package"
 * @generated
 */
public interface IfcBrickPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "ifcBrick";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/ifcbrickconvert/IfcBrick";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "ifcBrick";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  IfcBrickPackage eINSTANCE = org.xtext.ifcbrickconvert.ifcBrick.impl.IfcBrickPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.ifcbrickconvert.ifcBrick.impl.RootImpl <em>Root</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.ifcbrickconvert.ifcBrick.impl.RootImpl
   * @see org.xtext.ifcbrickconvert.ifcBrick.impl.IfcBrickPackageImpl#getRoot()
   * @generated
   */
  int ROOT = 0;

  /**
   * The feature id for the '<em><b>Header</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOT__HEADER = 0;

  /**
   * The feature id for the '<em><b>Data</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOT__DATA = 1;

  /**
   * The number of structural features of the '<em>Root</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.ifcbrickconvert.ifcBrick.impl.HeaderImpl <em>Header</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.ifcbrickconvert.ifcBrick.impl.HeaderImpl
   * @see org.xtext.ifcbrickconvert.ifcBrick.impl.IfcBrickPackageImpl#getHeader()
   * @generated
   */
  int HEADER = 1;

  /**
   * The feature id for the '<em><b>Header Entities</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HEADER__HEADER_ENTITIES = 0;

  /**
   * The number of structural features of the '<em>Header</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HEADER_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.ifcbrickconvert.ifcBrick.impl.DataImpl <em>Data</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.ifcbrickconvert.ifcBrick.impl.DataImpl
   * @see org.xtext.ifcbrickconvert.ifcBrick.impl.IfcBrickPackageImpl#getData()
   * @generated
   */
  int DATA = 2;

  /**
   * The feature id for the '<em><b>Entity With Ids</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA__ENTITY_WITH_IDS = 0;

  /**
   * The number of structural features of the '<em>Data</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.ifcbrickconvert.ifcBrick.impl.EntityImpl <em>Entity</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.ifcbrickconvert.ifcBrick.impl.EntityImpl
   * @see org.xtext.ifcbrickconvert.ifcBrick.impl.IfcBrickPackageImpl#getEntity()
   * @generated
   */
  int ENTITY = 3;

  /**
   * The feature id for the '<em><b>Definition</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY__DEFINITION = 0;

  /**
   * The feature id for the '<em><b>Attribute Collection</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY__ATTRIBUTE_COLLECTION = 1;

  /**
   * The number of structural features of the '<em>Entity</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.ifcbrickconvert.ifcBrick.impl.EntityWithIdImpl <em>Entity With Id</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.ifcbrickconvert.ifcBrick.impl.EntityWithIdImpl
   * @see org.xtext.ifcbrickconvert.ifcBrick.impl.IfcBrickPackageImpl#getEntityWithId()
   * @generated
   */
  int ENTITY_WITH_ID = 4;

  /**
   * The feature id for the '<em><b>Eid</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY_WITH_ID__EID = 0;

  /**
   * The feature id for the '<em><b>Entity</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY_WITH_ID__ENTITY = 1;

  /**
   * The number of structural features of the '<em>Entity With Id</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY_WITH_ID_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.ifcbrickconvert.ifcBrick.impl.EntityTerminatedImpl <em>Entity Terminated</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.ifcbrickconvert.ifcBrick.impl.EntityTerminatedImpl
   * @see org.xtext.ifcbrickconvert.ifcBrick.impl.IfcBrickPackageImpl#getEntityTerminated()
   * @generated
   */
  int ENTITY_TERMINATED = 5;

  /**
   * The feature id for the '<em><b>Entity</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY_TERMINATED__ENTITY = 0;

  /**
   * The number of structural features of the '<em>Entity Terminated</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY_TERMINATED_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.ifcbrickconvert.ifcBrick.impl.AttributeCollectionImpl <em>Attribute Collection</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.ifcbrickconvert.ifcBrick.impl.AttributeCollectionImpl
   * @see org.xtext.ifcbrickconvert.ifcBrick.impl.IfcBrickPackageImpl#getAttributeCollection()
   * @generated
   */
  int ATTRIBUTE_COLLECTION = 6;

  /**
   * The feature id for the '<em><b>Attributes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE_COLLECTION__ATTRIBUTES = 0;

  /**
   * The number of structural features of the '<em>Attribute Collection</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE_COLLECTION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.ifcbrickconvert.ifcBrick.impl.AttributeImpl <em>Attribute</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.ifcbrickconvert.ifcBrick.impl.AttributeImpl
   * @see org.xtext.ifcbrickconvert.ifcBrick.impl.IfcBrickPackageImpl#getAttribute()
   * @generated
   */
  int ATTRIBUTE = 7;

  /**
   * The feature id for the '<em><b>X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE__X = 0;

  /**
   * The feature id for the '<em><b>Eid</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE__EID = 1;

  /**
   * The feature id for the '<em><b>C</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE__C = 2;

  /**
   * The feature id for the '<em><b>E</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE__E = 3;

  /**
   * The feature id for the '<em><b>Ac</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE__AC = 4;

  /**
   * The feature id for the '<em><b>U</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE__U = 5;

  /**
   * The feature id for the '<em><b>S</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE__S = 6;

  /**
   * The feature id for the '<em><b>I</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE__I = 7;

  /**
   * The feature id for the '<em><b>D</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE__D = 8;

  /**
   * The feature id for the '<em><b>N</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE__N = 9;

  /**
   * The number of structural features of the '<em>Attribute</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE_FEATURE_COUNT = 10;

  /**
   * The meta object id for the '{@link org.xtext.ifcbrickconvert.ifcBrick.impl.EntIdImpl <em>Ent Id</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.ifcbrickconvert.ifcBrick.impl.EntIdImpl
   * @see org.xtext.ifcbrickconvert.ifcBrick.impl.IfcBrickPackageImpl#getEntId()
   * @generated
   */
  int ENT_ID = 8;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENT_ID__ID = 0;

  /**
   * The number of structural features of the '<em>Ent Id</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENT_ID_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.ifcbrickconvert.ifcBrick.impl.CSVImpl <em>CSV</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.ifcbrickconvert.ifcBrick.impl.CSVImpl
   * @see org.xtext.ifcbrickconvert.ifcBrick.impl.IfcBrickPackageImpl#getCSV()
   * @generated
   */
  int CSV = 9;

  /**
   * The feature id for the '<em><b>A</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CSV__A = 0;

  /**
   * The feature id for the '<em><b>B</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CSV__B = 1;

  /**
   * The number of structural features of the '<em>CSV</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CSV_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link org.xtext.ifcbrickconvert.ifcBrick.Root <em>Root</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Root</em>'.
   * @see org.xtext.ifcbrickconvert.ifcBrick.Root
   * @generated
   */
  EClass getRoot();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.ifcbrickconvert.ifcBrick.Root#getHeader <em>Header</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Header</em>'.
   * @see org.xtext.ifcbrickconvert.ifcBrick.Root#getHeader()
   * @see #getRoot()
   * @generated
   */
  EReference getRoot_Header();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.ifcbrickconvert.ifcBrick.Root#getData <em>Data</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Data</em>'.
   * @see org.xtext.ifcbrickconvert.ifcBrick.Root#getData()
   * @see #getRoot()
   * @generated
   */
  EReference getRoot_Data();

  /**
   * Returns the meta object for class '{@link org.xtext.ifcbrickconvert.ifcBrick.Header <em>Header</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Header</em>'.
   * @see org.xtext.ifcbrickconvert.ifcBrick.Header
   * @generated
   */
  EClass getHeader();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.ifcbrickconvert.ifcBrick.Header#getHeaderEntities <em>Header Entities</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Header Entities</em>'.
   * @see org.xtext.ifcbrickconvert.ifcBrick.Header#getHeaderEntities()
   * @see #getHeader()
   * @generated
   */
  EReference getHeader_HeaderEntities();

  /**
   * Returns the meta object for class '{@link org.xtext.ifcbrickconvert.ifcBrick.Data <em>Data</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Data</em>'.
   * @see org.xtext.ifcbrickconvert.ifcBrick.Data
   * @generated
   */
  EClass getData();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.ifcbrickconvert.ifcBrick.Data#getEntityWithIds <em>Entity With Ids</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Entity With Ids</em>'.
   * @see org.xtext.ifcbrickconvert.ifcBrick.Data#getEntityWithIds()
   * @see #getData()
   * @generated
   */
  EReference getData_EntityWithIds();

  /**
   * Returns the meta object for class '{@link org.xtext.ifcbrickconvert.ifcBrick.Entity <em>Entity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Entity</em>'.
   * @see org.xtext.ifcbrickconvert.ifcBrick.Entity
   * @generated
   */
  EClass getEntity();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.ifcbrickconvert.ifcBrick.Entity#getDefinition <em>Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Definition</em>'.
   * @see org.xtext.ifcbrickconvert.ifcBrick.Entity#getDefinition()
   * @see #getEntity()
   * @generated
   */
  EAttribute getEntity_Definition();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.ifcbrickconvert.ifcBrick.Entity#getAttributeCollection <em>Attribute Collection</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Attribute Collection</em>'.
   * @see org.xtext.ifcbrickconvert.ifcBrick.Entity#getAttributeCollection()
   * @see #getEntity()
   * @generated
   */
  EReference getEntity_AttributeCollection();

  /**
   * Returns the meta object for class '{@link org.xtext.ifcbrickconvert.ifcBrick.EntityWithId <em>Entity With Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Entity With Id</em>'.
   * @see org.xtext.ifcbrickconvert.ifcBrick.EntityWithId
   * @generated
   */
  EClass getEntityWithId();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.ifcbrickconvert.ifcBrick.EntityWithId#getEid <em>Eid</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Eid</em>'.
   * @see org.xtext.ifcbrickconvert.ifcBrick.EntityWithId#getEid()
   * @see #getEntityWithId()
   * @generated
   */
  EReference getEntityWithId_Eid();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.ifcbrickconvert.ifcBrick.EntityWithId#getEntity <em>Entity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Entity</em>'.
   * @see org.xtext.ifcbrickconvert.ifcBrick.EntityWithId#getEntity()
   * @see #getEntityWithId()
   * @generated
   */
  EReference getEntityWithId_Entity();

  /**
   * Returns the meta object for class '{@link org.xtext.ifcbrickconvert.ifcBrick.EntityTerminated <em>Entity Terminated</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Entity Terminated</em>'.
   * @see org.xtext.ifcbrickconvert.ifcBrick.EntityTerminated
   * @generated
   */
  EClass getEntityTerminated();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.ifcbrickconvert.ifcBrick.EntityTerminated#getEntity <em>Entity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Entity</em>'.
   * @see org.xtext.ifcbrickconvert.ifcBrick.EntityTerminated#getEntity()
   * @see #getEntityTerminated()
   * @generated
   */
  EReference getEntityTerminated_Entity();

  /**
   * Returns the meta object for class '{@link org.xtext.ifcbrickconvert.ifcBrick.AttributeCollection <em>Attribute Collection</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Attribute Collection</em>'.
   * @see org.xtext.ifcbrickconvert.ifcBrick.AttributeCollection
   * @generated
   */
  EClass getAttributeCollection();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.ifcbrickconvert.ifcBrick.AttributeCollection#getAttributes <em>Attributes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Attributes</em>'.
   * @see org.xtext.ifcbrickconvert.ifcBrick.AttributeCollection#getAttributes()
   * @see #getAttributeCollection()
   * @generated
   */
  EReference getAttributeCollection_Attributes();

  /**
   * Returns the meta object for class '{@link org.xtext.ifcbrickconvert.ifcBrick.Attribute <em>Attribute</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Attribute</em>'.
   * @see org.xtext.ifcbrickconvert.ifcBrick.Attribute
   * @generated
   */
  EClass getAttribute();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.ifcbrickconvert.ifcBrick.Attribute#getX <em>X</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>X</em>'.
   * @see org.xtext.ifcbrickconvert.ifcBrick.Attribute#getX()
   * @see #getAttribute()
   * @generated
   */
  EAttribute getAttribute_X();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.ifcbrickconvert.ifcBrick.Attribute#getEid <em>Eid</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Eid</em>'.
   * @see org.xtext.ifcbrickconvert.ifcBrick.Attribute#getEid()
   * @see #getAttribute()
   * @generated
   */
  EReference getAttribute_Eid();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.ifcbrickconvert.ifcBrick.Attribute#getC <em>C</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>C</em>'.
   * @see org.xtext.ifcbrickconvert.ifcBrick.Attribute#getC()
   * @see #getAttribute()
   * @generated
   */
  EReference getAttribute_C();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.ifcbrickconvert.ifcBrick.Attribute#getE <em>E</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>E</em>'.
   * @see org.xtext.ifcbrickconvert.ifcBrick.Attribute#getE()
   * @see #getAttribute()
   * @generated
   */
  EReference getAttribute_E();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.ifcbrickconvert.ifcBrick.Attribute#getAc <em>Ac</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Ac</em>'.
   * @see org.xtext.ifcbrickconvert.ifcBrick.Attribute#getAc()
   * @see #getAttribute()
   * @generated
   */
  EReference getAttribute_Ac();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.ifcbrickconvert.ifcBrick.Attribute#getU <em>U</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>U</em>'.
   * @see org.xtext.ifcbrickconvert.ifcBrick.Attribute#getU()
   * @see #getAttribute()
   * @generated
   */
  EAttribute getAttribute_U();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.ifcbrickconvert.ifcBrick.Attribute#getS <em>S</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>S</em>'.
   * @see org.xtext.ifcbrickconvert.ifcBrick.Attribute#getS()
   * @see #getAttribute()
   * @generated
   */
  EAttribute getAttribute_S();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.ifcbrickconvert.ifcBrick.Attribute#getI <em>I</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>I</em>'.
   * @see org.xtext.ifcbrickconvert.ifcBrick.Attribute#getI()
   * @see #getAttribute()
   * @generated
   */
  EAttribute getAttribute_I();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.ifcbrickconvert.ifcBrick.Attribute#getD <em>D</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>D</em>'.
   * @see org.xtext.ifcbrickconvert.ifcBrick.Attribute#getD()
   * @see #getAttribute()
   * @generated
   */
  EAttribute getAttribute_D();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.ifcbrickconvert.ifcBrick.Attribute#getN <em>N</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>N</em>'.
   * @see org.xtext.ifcbrickconvert.ifcBrick.Attribute#getN()
   * @see #getAttribute()
   * @generated
   */
  EAttribute getAttribute_N();

  /**
   * Returns the meta object for class '{@link org.xtext.ifcbrickconvert.ifcBrick.EntId <em>Ent Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ent Id</em>'.
   * @see org.xtext.ifcbrickconvert.ifcBrick.EntId
   * @generated
   */
  EClass getEntId();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.ifcbrickconvert.ifcBrick.EntId#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id</em>'.
   * @see org.xtext.ifcbrickconvert.ifcBrick.EntId#getId()
   * @see #getEntId()
   * @generated
   */
  EAttribute getEntId_Id();

  /**
   * Returns the meta object for class '{@link org.xtext.ifcbrickconvert.ifcBrick.CSV <em>CSV</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>CSV</em>'.
   * @see org.xtext.ifcbrickconvert.ifcBrick.CSV
   * @generated
   */
  EClass getCSV();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.ifcbrickconvert.ifcBrick.CSV#getA <em>A</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>A</em>'.
   * @see org.xtext.ifcbrickconvert.ifcBrick.CSV#getA()
   * @see #getCSV()
   * @generated
   */
  EAttribute getCSV_A();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.ifcbrickconvert.ifcBrick.CSV#getB <em>B</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>B</em>'.
   * @see org.xtext.ifcbrickconvert.ifcBrick.CSV#getB()
   * @see #getCSV()
   * @generated
   */
  EAttribute getCSV_B();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  IfcBrickFactory getIfcBrickFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.ifcbrickconvert.ifcBrick.impl.RootImpl <em>Root</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.ifcbrickconvert.ifcBrick.impl.RootImpl
     * @see org.xtext.ifcbrickconvert.ifcBrick.impl.IfcBrickPackageImpl#getRoot()
     * @generated
     */
    EClass ROOT = eINSTANCE.getRoot();

    /**
     * The meta object literal for the '<em><b>Header</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROOT__HEADER = eINSTANCE.getRoot_Header();

    /**
     * The meta object literal for the '<em><b>Data</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROOT__DATA = eINSTANCE.getRoot_Data();

    /**
     * The meta object literal for the '{@link org.xtext.ifcbrickconvert.ifcBrick.impl.HeaderImpl <em>Header</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.ifcbrickconvert.ifcBrick.impl.HeaderImpl
     * @see org.xtext.ifcbrickconvert.ifcBrick.impl.IfcBrickPackageImpl#getHeader()
     * @generated
     */
    EClass HEADER = eINSTANCE.getHeader();

    /**
     * The meta object literal for the '<em><b>Header Entities</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference HEADER__HEADER_ENTITIES = eINSTANCE.getHeader_HeaderEntities();

    /**
     * The meta object literal for the '{@link org.xtext.ifcbrickconvert.ifcBrick.impl.DataImpl <em>Data</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.ifcbrickconvert.ifcBrick.impl.DataImpl
     * @see org.xtext.ifcbrickconvert.ifcBrick.impl.IfcBrickPackageImpl#getData()
     * @generated
     */
    EClass DATA = eINSTANCE.getData();

    /**
     * The meta object literal for the '<em><b>Entity With Ids</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DATA__ENTITY_WITH_IDS = eINSTANCE.getData_EntityWithIds();

    /**
     * The meta object literal for the '{@link org.xtext.ifcbrickconvert.ifcBrick.impl.EntityImpl <em>Entity</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.ifcbrickconvert.ifcBrick.impl.EntityImpl
     * @see org.xtext.ifcbrickconvert.ifcBrick.impl.IfcBrickPackageImpl#getEntity()
     * @generated
     */
    EClass ENTITY = eINSTANCE.getEntity();

    /**
     * The meta object literal for the '<em><b>Definition</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENTITY__DEFINITION = eINSTANCE.getEntity_Definition();

    /**
     * The meta object literal for the '<em><b>Attribute Collection</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENTITY__ATTRIBUTE_COLLECTION = eINSTANCE.getEntity_AttributeCollection();

    /**
     * The meta object literal for the '{@link org.xtext.ifcbrickconvert.ifcBrick.impl.EntityWithIdImpl <em>Entity With Id</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.ifcbrickconvert.ifcBrick.impl.EntityWithIdImpl
     * @see org.xtext.ifcbrickconvert.ifcBrick.impl.IfcBrickPackageImpl#getEntityWithId()
     * @generated
     */
    EClass ENTITY_WITH_ID = eINSTANCE.getEntityWithId();

    /**
     * The meta object literal for the '<em><b>Eid</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENTITY_WITH_ID__EID = eINSTANCE.getEntityWithId_Eid();

    /**
     * The meta object literal for the '<em><b>Entity</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENTITY_WITH_ID__ENTITY = eINSTANCE.getEntityWithId_Entity();

    /**
     * The meta object literal for the '{@link org.xtext.ifcbrickconvert.ifcBrick.impl.EntityTerminatedImpl <em>Entity Terminated</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.ifcbrickconvert.ifcBrick.impl.EntityTerminatedImpl
     * @see org.xtext.ifcbrickconvert.ifcBrick.impl.IfcBrickPackageImpl#getEntityTerminated()
     * @generated
     */
    EClass ENTITY_TERMINATED = eINSTANCE.getEntityTerminated();

    /**
     * The meta object literal for the '<em><b>Entity</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENTITY_TERMINATED__ENTITY = eINSTANCE.getEntityTerminated_Entity();

    /**
     * The meta object literal for the '{@link org.xtext.ifcbrickconvert.ifcBrick.impl.AttributeCollectionImpl <em>Attribute Collection</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.ifcbrickconvert.ifcBrick.impl.AttributeCollectionImpl
     * @see org.xtext.ifcbrickconvert.ifcBrick.impl.IfcBrickPackageImpl#getAttributeCollection()
     * @generated
     */
    EClass ATTRIBUTE_COLLECTION = eINSTANCE.getAttributeCollection();

    /**
     * The meta object literal for the '<em><b>Attributes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATTRIBUTE_COLLECTION__ATTRIBUTES = eINSTANCE.getAttributeCollection_Attributes();

    /**
     * The meta object literal for the '{@link org.xtext.ifcbrickconvert.ifcBrick.impl.AttributeImpl <em>Attribute</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.ifcbrickconvert.ifcBrick.impl.AttributeImpl
     * @see org.xtext.ifcbrickconvert.ifcBrick.impl.IfcBrickPackageImpl#getAttribute()
     * @generated
     */
    EClass ATTRIBUTE = eINSTANCE.getAttribute();

    /**
     * The meta object literal for the '<em><b>X</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTRIBUTE__X = eINSTANCE.getAttribute_X();

    /**
     * The meta object literal for the '<em><b>Eid</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATTRIBUTE__EID = eINSTANCE.getAttribute_Eid();

    /**
     * The meta object literal for the '<em><b>C</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATTRIBUTE__C = eINSTANCE.getAttribute_C();

    /**
     * The meta object literal for the '<em><b>E</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATTRIBUTE__E = eINSTANCE.getAttribute_E();

    /**
     * The meta object literal for the '<em><b>Ac</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATTRIBUTE__AC = eINSTANCE.getAttribute_Ac();

    /**
     * The meta object literal for the '<em><b>U</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTRIBUTE__U = eINSTANCE.getAttribute_U();

    /**
     * The meta object literal for the '<em><b>S</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTRIBUTE__S = eINSTANCE.getAttribute_S();

    /**
     * The meta object literal for the '<em><b>I</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTRIBUTE__I = eINSTANCE.getAttribute_I();

    /**
     * The meta object literal for the '<em><b>D</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTRIBUTE__D = eINSTANCE.getAttribute_D();

    /**
     * The meta object literal for the '<em><b>N</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTRIBUTE__N = eINSTANCE.getAttribute_N();

    /**
     * The meta object literal for the '{@link org.xtext.ifcbrickconvert.ifcBrick.impl.EntIdImpl <em>Ent Id</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.ifcbrickconvert.ifcBrick.impl.EntIdImpl
     * @see org.xtext.ifcbrickconvert.ifcBrick.impl.IfcBrickPackageImpl#getEntId()
     * @generated
     */
    EClass ENT_ID = eINSTANCE.getEntId();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENT_ID__ID = eINSTANCE.getEntId_Id();

    /**
     * The meta object literal for the '{@link org.xtext.ifcbrickconvert.ifcBrick.impl.CSVImpl <em>CSV</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.ifcbrickconvert.ifcBrick.impl.CSVImpl
     * @see org.xtext.ifcbrickconvert.ifcBrick.impl.IfcBrickPackageImpl#getCSV()
     * @generated
     */
    EClass CSV = eINSTANCE.getCSV();

    /**
     * The meta object literal for the '<em><b>A</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CSV__A = eINSTANCE.getCSV_A();

    /**
     * The meta object literal for the '<em><b>B</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CSV__B = eINSTANCE.getCSV_B();

  }

} //IfcBrickPackage
