/*
 * generated by Xtext 2.12.0
 */
package org.xtext.ifcbrickconvert.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.ifcbrickconvert.parser.antlr.internal.InternalIfcBrickParser;
import org.xtext.ifcbrickconvert.services.IfcBrickGrammarAccess;

public class IfcBrickParser extends AbstractAntlrParser {

	@Inject
	private IfcBrickGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalIfcBrickParser createParser(XtextTokenStream stream) {
		return new InternalIfcBrickParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Root";
	}

	public IfcBrickGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(IfcBrickGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
