/*
 * generated by Xtext 2.12.0
 */
package org.xtext.ifcbrickconvert.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractIfcBrickScopeProvider extends DelegatingScopeProvider {
}
