/**
 * generated by Xtext 2.12.0
 */
package org.xtext.ifcbrickconvert.validation;

import org.xtext.ifcbrickconvert.validation.AbstractIfcBrickValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class IfcBrickValidator extends AbstractIfcBrickValidator {
}
