/*
 * generated by Xtext 2.12.0
 */
package org.xtext.ifcbrickconvert.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.ifcbrickconvert.mydsl.ui.internal.MydslActivator;

public class IfcBrickUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MydslActivator.getInstance().getInjector("org.xtext.ifcbrickconvert.IfcBrick");
	}

}
