/**
 * generated by Xtext 2.12.0
 */
package org.xtext.ifcbrickconvert;

import org.xtext.ifcbrickconvert.IfcBrickStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class IfcBrickStandaloneSetup extends IfcBrickStandaloneSetupGenerated {
  public static void doSetup() {
    new IfcBrickStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
