/**
 * generated by Xtext 2.12.0
 */
package org.xtext.ifcbrickconvert.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.ifcbrickconvert.ui.AbstractIfcBrickUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class IfcBrickUiModule extends AbstractIfcBrickUiModule {
  public IfcBrickUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
