/**
 * generated by Xtext 2.12.0
 */
package org.xtext.ifcbrickconvert.ide;

import org.xtext.ifcbrickconvert.ide.AbstractIfcBrickIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class IfcBrickIdeModule extends AbstractIfcBrickIdeModule {
}
