/*
 * generated by Xtext 2.12.0
 */
package org.xtext.ifcbrickconvert


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class IfcBrickStandaloneSetup extends IfcBrickStandaloneSetupGenerated {

	def static void doSetup() {
		new IfcBrickStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
